automatically link/unlink the agent on machine start/stop
singleplatform-eng/ansible-role-nessus-agent pull request #4
Opened 2017-12-13 08:33 UTC by afeld

At @GSA, we were running into the issue of Nessus Agents remaining linked even after their virtual machine was gone. Rather than having Ansible do the linking, this instead uses a systemd service to link and unlink the Agent when the service (and thus the machine) is started or stopped, respectively.

I'm new to Nessus and writing systemd services, so it's very possible there are downsides of this approach I'm not thinking of. Feedback welcome!

2017-12-13 15:30 UTC, wwaltersp requested changes
Hey, We are currently using this role with ubuntu 14.04 and intend to have this role continue to work with versions prior to 16.04. In order to consider this PR we would need it to support the current method and only use the systemd method for systems that use it as the default service manager.

2017-12-13 15:30 UTC, wwaltersp commented on handlers/main.yml
> +  systemd: name=nessus_link state=restarted daemon_reload=true
Hey, We are currently using this role with ubuntu 14.04 and intend to have this role continue to work with versions prior to 16.04. In order to consider this PR we would need it to support the current method and only use the systemd method for systems that use it as the default service manager.

2017-12-13 16:11 UTC, afeld commented
Cool, understood. What if an equivalent Upstart script were used in the case of Ubuntu 14? Thanks for the quick response!

2017-12-13 16:17 UTC, wwaltersp commented
If you support both upstart or preserve the current behavior and systemd depending on release version, we can review the changes for acceptance. Any tests to demonstrate behavior are also appreciated.

2017-12-17 20:46 UTC, afeld commented
From one of our security folks, who has been using Nessus for a while:

> unlink script on shutdown...This has proven to be problematic in that an unlink will remove all previous information about the system and affects Tenable Security Center reporting. Tenable also has added a configuration item in TSC that will auto-remove a registered agent if it has not checked in for a certain number of days.

We’ll probably try using that feature instead. 

https://docs.tenable.com/releasenotes/tenableio/tenableio3.htm

Thanks anyway!

2017-12-17 20:46 UTC, closed without merging